// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package accrual

import (
	"context"

	"github.com/olelishna/go-shop-diploma/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClientInterface creates a new instance of MockAccrualClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClientInterface {
	mock := &MockAccrualClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClientInterface is an autogenerated mock type for the AccrualClientInterface type
type MockAccrualClientInterface struct {
	mock.Mock
}

type MockAccrualClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClientInterface) EXPECT() *MockAccrualClientInterface_Expecter {
	return &MockAccrualClientInterface_Expecter{mock: &_m.Mock}
}

// GetAccrual provides a mock function for the type MockAccrualClientInterface
func (_mock *MockAccrualClientInterface) GetAccrual(ctx context.Context, orderNumber string) (*model.AccrualResponse, error) {
	ret := _mock.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetAccrual")
	}

	var r0 *model.AccrualResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AccrualResponse, error)); ok {
		return returnFunc(ctx, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AccrualResponse); ok {
		r0 = returnFunc(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccrualResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClientInterface_GetAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccrual'
type MockAccrualClientInterface_GetAccrual_Call struct {
	*mock.Call
}

// GetAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockAccrualClientInterface_Expecter) GetAccrual(ctx interface{}, orderNumber interface{}) *MockAccrualClientInterface_GetAccrual_Call {
	return &MockAccrualClientInterface_GetAccrual_Call{Call: _e.mock.On("GetAccrual", ctx, orderNumber)}
}

func (_c *MockAccrualClientInterface_GetAccrual_Call) Run(run func(ctx context.Context, orderNumber string)) *MockAccrualClientInterface_GetAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClientInterface_GetAccrual_Call) Return(accrualResponse *model.AccrualResponse, err error) *MockAccrualClientInterface_GetAccrual_Call {
	_c.Call.Return(accrualResponse, err)
	return _c
}

func (_c *MockAccrualClientInterface_GetAccrual_Call) RunAndReturn(run func(ctx context.Context, orderNumber string) (*model.AccrualResponse, error)) *MockAccrualClientInterface_GetAccrual_Call {
	_c.Call.Return(run)
	return _c
}
